#!/usr/bin/env python

import os
import sys
import argparse
from pathlib import Path


BASE_DIR = Path(os.path.dirname(os.path.abspath(__file__)))

CONTENTS = """
# Generated by Cargo
# will have compiled files and executables
/target/

# Remove Cargo.lock from gitignore if creating an executable, leave it for libraries
# More information here https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.htmlC
Cargo.lock

# These are backup files generated by rustfmt
**/*.rs.bk
"""


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("slug", metavar="SLUG")
    opts = parser.parse_args(sys.argv[1:])
    dest_dir = BASE_DIR / opts.slug / "rust"
    os.makedirs(dest_dir, exist_ok=True)
    os.chdir(dest_dir)
    os.system("cargo new --lib sol")
    with open(dest_dir / "sol" / ".gitignore", "w") as f:
        f.write(CONTENTS)
    print(dest_dir / "sol")
